stages:
  - build

variables:
  TTS_MODEL: "xtts"
  DOCKER_TAG: "latest"
  BASE_IMAGE_REPO: "erew123/"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"
  DOCKER_TLS_VERIFY: "1"

build-alltalk:
  stage: build
  timeout: 3h
  image: docker:27
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker info
    - docker build --pull
      --build-arg TTS_MODEL=$TTS_MODEL
      --build-arg DEEPSPEED_VERSION=0.17.2
      --build-arg DOCKER_TAG=$DOCKER_TAG
      --build-arg DOCKER_REPOSITORY=$BASE_IMAGE_REPO
      -t $CI_REGISTRY_IMAGE:latest-$TTS_MODEL
      .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest-$TTS_MODEL
      || (docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      && docker push $CI_REGISTRY_IMAGE:latest-$TTS_MODEL)
  tags:
    - docker
