stages:
  - build

variables:
  TTS_MODEL: "xtts"
  DOCKER_TAG: "latest"
  BASE_IMAGE_REPO: "erew123/"

build-alltalk:
  stage: build
  timeout: 3h
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf '%s:%s' "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest-$TTS_MODEL
      --build-arg TTS_MODEL=$TTS_MODEL
      --build-arg DEEPSPEED_VERSION=0.17.2
      --build-arg DOCKER_TAG=$DOCKER_TAG
      --build-arg DOCKER_REPOSITORY=$BASE_IMAGE_REPO
      --cache=true
      --cache-repo=$CI_REGISTRY_IMAGE/cache
      --snapshot-mode=redo
  tags:
    - docker
